-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
    INNER JOIN FISH_NAME_INFO AS N
    ON N.FISH_TYPE = I.FISH_TYPE
WHERE I.FISH_TYPE IN
    (SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)) 
ORDER BY I.ID;